spring:
  application:
    name: EscalaFacil
  datasource:
    url: jdbc:h2:mem:escalafacil
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    jwt-secret: "714215bdb849674c08d9a38f146d2d03d66a15754870206be2df3a4b80b0fbce" # crie um hash para colocar aqui
    jwt-expiration: 900000
